package com.walle.gankio.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.walle.gankio.data.local.entity.Collect;
import com.walle.gankio.data.local.entity.User;

import com.walle.gankio.greendao.CollectDao;
import com.walle.gankio.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CollectDao collectDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectDaoConfig = daoConfigMap.get(CollectDao.class).clone();
        collectDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        collectDao = new CollectDao(collectDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Collect.class, collectDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        collectDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CollectDao getCollectDao() {
        return collectDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
